### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by takeda** [srijs/rust-cfn#1]
@srijs are there plans to revive this (or maybe known alternative) or was this project abandoned?

I tried to use generator to update the code, but it not longer compiles for me.

**Comment by srijs** [comment]
Hey there!

It's not abandoned per-se, but I've not been using this in a while so I haven't been keeping up with the changing resource spec from AWS.

I've now fixed the generator and updated the resource spec. The new version (0.0.8) should hit crates.io in a minute.  Compile times are now higher with more services added, which you may notice (I think a good solution there might be to enable/disable certain service definitions via cargo features).

Generally happy to accept PRs as well if there's other things you'd like to change or fix up!

**Comment by srijs** [comment]
Let me know if this works for you for now, in which case I'd be inclined to close this issue.

**Comment by takeda** [comment]
Thank you, I am not sure I'm at a stage where I can make a PR, I started learning Rust literally last week, by trying to convert a simple Python code that used boto3 + Troposphere and seeing how it would look like in Rust.
I'm trying it now, but I think it will take me a while until I get things to work, lol.

BTW: based on the source, is it correct understanding, that the library doesn't support parameters?
https://github.com/srijs/rust-cfn/blob/1f4448585b9a129e38bbc693c29570e624e90ae5/src/lib.rs#L30-L37

**Comment by srijs** [comment]
Oh that's cool, welcome to Rust, and good luck with your project! :)

I haven't had much of a need for parameters yet, give that I've mainly used this library to generate templates from some inputs, meaning I can fill in the values directly into the template rather than using parameters. It shouldn't be too hard to add though if you need support for them.

I'll close out this issue for now (short answer: not abandoned, PRs welcome), but feel free to open new issues if you run into any problems later on!
